// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoa8zd2Thl2n4T69EjKwaQFWx6nOgddRA',
    appId: '1:957397072386:web:0c57a731b90a485ee2051b',
    messagingSenderId: '957397072386',
    projectId: 'caloriemate-32779',
    authDomain: 'caloriemate-32779.firebaseapp.com',
    storageBucket: 'caloriemate-32779.firebasestorage.app',
    measurementId: 'G-MEM78XJVPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Wh1Nwg8zusdmJX1XhKOyjFEEQohdZyo',
    appId: '1:957397072386:android:5916aea3f8d389a6e2051b',
    messagingSenderId: '957397072386',
    projectId: 'caloriemate-32779',
    storageBucket: 'caloriemate-32779.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxMD4uUa4DVTnWFauC6NMX65jFsCcCFfc',
    appId: '1:957397072386:ios:f6eb2e8036c584fde2051b',
    messagingSenderId: '957397072386',
    projectId: 'caloriemate-32779',
    storageBucket: 'caloriemate-32779.firebasestorage.app',
    iosBundleId: 'com.example.caloriemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxMD4uUa4DVTnWFauC6NMX65jFsCcCFfc',
    appId: '1:957397072386:ios:f6eb2e8036c584fde2051b',
    messagingSenderId: '957397072386',
    projectId: 'caloriemate-32779',
    storageBucket: 'caloriemate-32779.firebasestorage.app',
    iosBundleId: 'com.example.caloriemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoa8zd2Thl2n4T69EjKwaQFWx6nOgddRA',
    appId: '1:957397072386:web:c459b618f6d705b2e2051b',
    messagingSenderId: '957397072386',
    projectId: 'caloriemate-32779',
    authDomain: 'caloriemate-32779.firebaseapp.com',
    storageBucket: 'caloriemate-32779.firebasestorage.app',
    measurementId: 'G-XR4MEEBVLC',
  );
}
